import type { AIRelease } from '../types/releases';
import type { DictionaryTerm } from '../types/dictionary';
import { uid, now } from './utils';

export const seedReleases: AIRelease[] = [
  // ─── Past 6 months — Anthropic ────────────────────────────────────────────
  { id: uid(), name: 'Claude Opus 4.7', company: 'Anthropic', releaseDate: '2026-03-10', description: 'Flagship Opus tier. State-of-the-art agentic reasoning, deeper coding/tool-use, and improved long-context stability. Default for high-stakes work in Claude Code and the API.', tags: ['model', 'opus', 'flagship'], link: 'https://www.anthropic.com/news/claude-opus-4-7', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude Opus 4.6', company: 'Anthropic', releaseDate: '2026-01-22', description: 'Powers Claude Code Fast mode — Opus-tier quality with faster output. First Opus release tuned for real-time agent loops.', tags: ['model', 'opus', 'fast-mode'], link: 'https://www.anthropic.com/news/claude-opus-4-6', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude Sonnet 4.6', company: 'Anthropic', releaseDate: '2025-12-08', description: 'Workhorse Sonnet refresh. Better instruction following, more reliable JSON/tool-use, and improved multilingual writing at the same price point.', tags: ['model', 'sonnet'], link: 'https://www.anthropic.com/news/claude-sonnet-4-6', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude Haiku 4.5', company: 'Anthropic', releaseDate: '2025-10-01', description: 'Fast, cheap Haiku tier with near-Sonnet quality on many benchmarks. Designed for high-throughput agent swarms and latency-sensitive UX.', tags: ['model', 'haiku', 'fast'], link: 'https://www.anthropic.com/news/claude-haiku-4-5', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude Sonnet 4.5', company: 'Anthropic', releaseDate: '2025-09-29', description: 'Best coding model at release — leads SWE-bench and Terminal-Bench. Ships with 1M token context in the API for large codebases.', tags: ['model', 'sonnet', 'coding', 'long-context'], link: 'https://www.anthropic.com/news/claude-sonnet-4-5', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude Agent SDK', company: 'Anthropic', releaseDate: '2025-10-15', description: 'Build custom coding agents with the same primitives that power Claude Code — sub-agents, hooks, permissions, and MCP integrations.', tags: ['sdk', 'agents', 'claude-code'], link: 'https://docs.anthropic.com/en/api/agent-sdk', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude for Chrome', company: 'Anthropic', releaseDate: '2025-11-05', description: 'Browser extension that lets Claude see and act on the page you are reading. Autofill, summarize, research, and take actions across tabs.', tags: ['extension', 'agents', 'browser'], link: 'https://www.anthropic.com/news/claude-for-chrome', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude Code 2.0', company: 'Anthropic', releaseDate: '2025-11-18', description: 'Major Claude Code refresh — /fast mode on Opus 4.6, new sub-agent system, improved hook API, and native IDE status-line integration.', tags: ['claude-code', 'cli', 'tooling'], link: 'https://www.anthropic.com/news/claude-code-2', createdAt: now(), updatedAt: now() },

  // ─── Past 6 months — Google / DeepMind ───────────────────────────────────
  { id: uid(), name: 'Gemini 3 Pro', company: 'Google', releaseDate: '2026-02-12', description: 'Next-gen flagship with massively improved reasoning, coding, and agentic task completion. Default in the Gemini app and AI Studio.', tags: ['model', 'gemini', 'flagship'], link: 'https://blog.google/technology/google-deepmind/gemini-3/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Gemini 3 Deep Think', company: 'Google', releaseDate: '2026-02-12', description: 'Extended reasoning mode for Gemini 3 Pro. Thinks longer on hard math, coding, and research questions. Available to Google AI Ultra subscribers.', tags: ['model', 'reasoning', 'thinking'], link: 'https://blog.google/technology/google-deepmind/gemini-3-deep-think/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Nano Banana Pro', company: 'Google', releaseDate: '2025-11-20', description: 'Image generation and editing model built on Gemini 3. Character consistency, text in images, and precise multi-image composition.', tags: ['image', 'multimodal', 'generation'], link: 'https://blog.google/technology/ai/nano-banana-pro/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Veo 3.1', company: 'Google', releaseDate: '2025-10-28', description: 'Video generation model with native audio, longer shots, and stronger prompt adherence. Available in the Gemini app and Vertex AI.', tags: ['video', 'multimodal', 'generation'], link: 'https://deepmind.google/technologies/veo/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Gemini 2.5 Computer Use', company: 'Google', releaseDate: '2025-10-07', description: 'A browser-native agent model that can navigate, click, type, and complete tasks on real web pages. Available to developers in preview.', tags: ['agents', 'browser', 'tool-use'], link: 'https://blog.google/technology/google-deepmind/gemini-computer-use-model/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Gemini Agent Mode', company: 'Google', releaseDate: '2026-01-14', description: 'Multi-step agentic mode in the Gemini app. Books travel, researches across tabs, fills forms, and follows up without constant prompts.', tags: ['agents', 'gemini-app'], link: 'https://blog.google/products/gemini/agent-mode/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Project Mariner GA', company: 'Google', releaseDate: '2025-12-03', description: 'Research prototype for agentic web interaction moves to general availability. Integrated with Gemini 3 and exposed via the Agent API.', tags: ['agents', 'browser', 'research'], link: 'https://deepmind.google/technologies/project-mariner/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'NotebookLM Video Overviews', company: 'Google', releaseDate: '2025-10-17', description: 'NotebookLM can now generate narrated video summaries from your uploaded sources, not just audio overviews. Great for visual learners.', tags: ['notebooklm', 'video', 'research'], link: 'https://blog.google/technology/google-labs/notebooklm-video-overviews/', createdAt: now(), updatedAt: now() },

  // ─── Historical — kept for reference ─────────────────────────────────────
  { id: uid(), name: 'Claude 3.7 Sonnet', company: 'Anthropic', releaseDate: '2025-02-24', description: 'Extended thinking mode — model reasons step-by-step before answering. State of the art on coding benchmarks.', tags: ['reasoning', 'thinking', 'coding'], link: 'https://www.anthropic.com/news/claude-3-7-sonnet', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Gemini 2.0 Flash', company: 'Google', releaseDate: '2025-02-05', description: 'Fast, low-cost model with native image and audio output. First model with native tool use built in.', tags: ['fast', 'multimodal', 'tool-use'], link: 'https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Claude 3.5 Sonnet', company: 'Anthropic', releaseDate: '2024-06-20', description: 'Best-in-class coding and reasoning. Introduced Artifacts — Claude can write and run code in-browser.', tags: ['coding', 'reasoning', 'artifacts'], link: 'https://www.anthropic.com/news/claude-3-5-sonnet', createdAt: now(), updatedAt: now() },
  { id: uid(), name: 'Gemini 1.5 Pro', company: 'Google', releaseDate: '2024-02-15', description: 'Flagship model with a 1M token context window. Handles hour-long videos and large codebases in a single prompt.', tags: ['long-context', 'video', 'multimodal'], link: 'https://blog.google/technology/ai/google-gemini-next-generation-model-february-2024/', createdAt: now(), updatedAt: now() },
];

export const seedTerms: DictionaryTerm[] = [
  { id: uid(), term: 'LLM', plainDefinition: 'A Large Language Model is an AI trained on enormous amounts of text. It can write, summarize, code, and answer questions by predicting what words come next.', category: 'model', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'RAG', plainDefinition: 'Retrieval-Augmented Generation — a way to give an AI access to your own documents so it can answer questions about them accurately, instead of making things up.', category: 'technique', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Fine-tuning', plainDefinition: 'Taking an existing AI model and training it further on a smaller, specific dataset — like retraining a chef to specialize in Italian cuisine.', category: 'technique', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Prompt Engineering', plainDefinition: 'The skill of writing instructions to an AI model in a way that gets the best, most useful response. Think of it as learning how to ask questions well.', category: 'technique', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Inference', plainDefinition: 'The moment an AI actually runs and produces an answer. Inference is what happens every time you send a message — the model computes its response.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Hallucination', plainDefinition: 'When an AI confidently states something that is completely made up — like inventing a fake citation or saying a person exists when they don\'t.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Embedding', plainDefinition: 'A way of converting words or ideas into numbers so a computer can compare them by meaning. Similar ideas end up as similar numbers.', category: 'technique', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Tokenizer', plainDefinition: 'Before an AI reads your text, it chops it into small pieces called tokens — roughly word-parts. This affects how much text the model can process at once.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Context Window', plainDefinition: 'The maximum amount of text an AI can "see" at once — like short-term memory. Once text falls outside the window, the model forgets it.', category: 'model', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Agent', plainDefinition: 'An AI that doesn\'t just answer questions — it takes actions. It can search the web, run code, and loop on tasks without a human at each step.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'MCP', plainDefinition: 'Model Context Protocol — a standard way for AI models to connect to external tools like databases, apps, or APIs. Makes it easy to plug new capabilities into an AI.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Multimodal', plainDefinition: 'An AI that works with more than just text — it can also understand images, audio, or video. A multimodal model can look at a photo and describe it.', category: 'model', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'RLHF', plainDefinition: 'Reinforcement Learning from Human Feedback — a training method where humans rate the AI\'s answers, and the AI learns to produce responses humans prefer.', category: 'technique', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Latency', plainDefinition: 'How long you wait for the AI to respond. Low latency means it answers fast; high latency means you\'re sitting there watching a spinner.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Foundation Model', plainDefinition: 'A large, general-purpose AI trained on massive data that can be adapted for many tasks. GPT-4 and Claude are foundation models — the base everything else builds on.', category: 'model', createdAt: now(), updatedAt: now() },

  // Models & Usage
  { id: uid(), term: 'Token', plainDefinition: 'The basic unit AI models process. Roughly ¾ of a word — "Hello world" is about 2 tokens. Bills and rate limits are measured in tokens, not messages.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Token Usage', plainDefinition: 'The total count of tokens sent (your prompt) plus tokens received (the model\'s reply). Used to calculate API costs and enforce rate limits.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Temperature', plainDefinition: 'A dial controlling how random AI output is. Low = predictable, consistent answers. High = creative, variable, sometimes chaotic.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Streaming', plainDefinition: 'Text appearing word-by-word as the AI generates it, instead of waiting for the full response. Most chat interfaces stream output by default.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Knowledge Cutoff', plainDefinition: 'The date past which an AI model has no training data. Events after the cutoff are unknown to the model unless it can search the web.', category: 'model', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Completion', plainDefinition: 'The text an AI model generates in response to a prompt. Also called a response or output. One prompt + one completion = one inference round.', category: 'concept', createdAt: now(), updatedAt: now() },

  // Prompts & Behavior
  { id: uid(), term: 'Prompt', plainDefinition: 'The input you give to an AI model — the question, instruction, or context that triggers a response. Everything before the model starts generating.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'System Prompt', plainDefinition: 'Hidden instructions that shape the AI\'s behavior before the conversation starts. Defines persona, constraints, and rules — you never see it, but it runs first.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Jailbreak', plainDefinition: 'Tricking an AI into ignoring its safety rules or producing restricted content by framing the request cleverly. Usually patched as models improve.', category: 'safety', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Guardrails', plainDefinition: 'Safety filters and rules baked into an AI model to prevent harmful, illegal, or policy-violating outputs. The model\'s built-in refusals and limits.', category: 'safety', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Alignment', plainDefinition: 'The research problem of making AI systems do what humans actually want, including sharing human values and being safe to deploy at scale.', category: 'safety', createdAt: now(), updatedAt: now() },

  // Interfaces & Protocols
  { id: uid(), term: 'Tool Use', plainDefinition: 'The ability for an AI to call external functions or APIs — like searching the web, running code, or reading a file — instead of just generating text.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Agentic Coding', plainDefinition: 'Letting an AI plan and execute multi-step coding tasks autonomously — it writes code, runs it, sees errors, and fixes them without hand-holding at each step.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Artifact', plainDefinition: 'A standalone rendered output in Claude.ai — an interactive HTML preview, document, or code block that the model generates and displays separately from the chat.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'API', plainDefinition: 'Application Programming Interface — how software talks to other software. An API lets your app request data or actions from a service without building it yourself.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'API Key', plainDefinition: 'A secret credential that authenticates access to an API. Treat it like a password — never share it, never commit it to code.', category: 'safety', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Rate Limit', plainDefinition: 'A cap on how many requests or tokens you can use per minute or day. Hit the limit and requests fail until the window resets.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'SDK', plainDefinition: 'Software Development Kit — an official code library that wraps an API, making it easier to call from a specific programming language like Python or TypeScript.', category: 'infrastructure', createdAt: now(), updatedAt: now() },

  // Advanced
  { id: uid(), term: 'Vector Database', plainDefinition: 'A database designed to store embeddings and find semantically similar items fast. Core infrastructure for RAG systems. Examples: Pinecone, Weaviate, pgvector.', category: 'data', createdAt: now(), updatedAt: now() },

  // Culture & Workflow
  { id: uid(), term: 'Vibe Coding', plainDefinition: 'Building software by describing the desired outcome to an AI rather than writing code yourself. Coined by Andrej Karpathy. Taste and judgment still matter.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Slop', plainDefinition: 'Generic, low-effort AI output that feels mass-produced and tasteless. The opposite of crafted, intentional work. The main failure mode of uncurated AI.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Dogfooding', plainDefinition: 'Using your own product as a real user would. Catches problems that specs and tests miss because you actually feel the pain of your own decisions.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Scaffolding', plainDefinition: 'The starter structure of a project — folder layout, config files, base components — before the real domain code is written. AI is very good at generating this.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Boilerplate', plainDefinition: 'Repetitive code that must exist but adds no unique value — setup, imports, config, CRUD. AI handles boilerplate well so humans can focus on the interesting parts.', category: 'concept', createdAt: now(), updatedAt: now() },

  // AI & Claude — additional terms
  { id: uid(), term: 'Model', plainDefinition: 'The specific AI brain doing the work (e.g., Claude Opus 4.7, Sonnet 4.6). Bigger/newer models are generally smarter but slower and more expensive to run.', category: 'model', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'CLI', plainDefinition: 'Command Line Interface — typing commands in Terminal or PowerShell instead of clicking buttons. Most developer tools (git, npm, Claude Code) are CLI-based.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Terminal / Shell', plainDefinition: 'The text-based window where you type commands. Common shells: zsh and bash on Mac/Linux, PowerShell on Windows. Where you run git, npm, and Claude Code.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'MCP Server', plainDefinition: 'A connector that exposes one app\'s capabilities to an AI via the Model Context Protocol. Each server gives the AI new tools — Gmail, GitHub, filesystem, and more.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Claude Code', plainDefinition: 'Anthropic\'s terminal-based agentic coding tool. Understands your codebase and can plan, edit, run, and fix code autonomously from the command line.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Taste', plainDefinition: 'Human judgment on what\'s good — design, prose, architecture, UX. The rare skill AI can assist with but not replace. Your curatorial eye is the real differentiator.', category: 'concept', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Shipping', plainDefinition: 'Actually releasing something to users. The opposite of endless tinkering. In software culture, shipping is the only thing that counts.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Yak Shaving', plainDefinition: 'Doing infinite prerequisite side tasks before you can start the actual task. Updating a tool to write a script to fix a config to build the feature.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Refactor', plainDefinition: 'Rewriting existing code to be cleaner or more maintainable without changing what it does. No new features — just better structure.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Debug', plainDefinition: 'Finding and fixing broken or unexpected behavior in code. The process of diagnosing why something isn\'t working as intended.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Localhost', plainDefinition: 'Your own computer acting as a web server. localhost:3000 means "open port 3000 on this machine." Used during development before deploying publicly.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Frontend / Backend', plainDefinition: 'Frontend = what users see in their browser (HTML, CSS, JS). Backend = the server logic and database that users never interact with directly.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Framework', plainDefinition: 'Prebuilt structure for building apps — handles routing, state, tooling, and conventions. React, Next.js, and Svelte are frontend frameworks.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Environment Variable', plainDefinition: 'A secret or config value stored outside your code, typically in a .env file. API keys, database URLs, and feature flags live here — never hard-code them.', category: 'general', createdAt: now(), updatedAt: now() },

  // Languages
  { id: uid(), term: 'HTML', plainDefinition: 'HyperText Markup Language — the skeleton of a webpage. Defines structure with tags like <div>, <p>, <img>. Not a programming language; it\'s markup.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'CSS', plainDefinition: 'Cascading Style Sheets — the styling layer of the web. Controls colors, fonts, spacing, and layout. Works alongside HTML to make pages look good.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'JavaScript', plainDefinition: 'JS — the programming language of the browser. Makes pages interactive. Also runs on servers via Node.js. The most widely deployed language in the world.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'TypeScript', plainDefinition: 'TS — JavaScript with type-checking added. Catches bugs before you run the code. Industry standard for larger JS projects; compiles down to plain JavaScript.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Python', plainDefinition: 'Beginner-friendly, readable language. Dominant in AI, data science, scripting, and automation. The default language for ML research and most AI tooling.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Java', plainDefinition: 'Enterprise workhorse language. Powers Android apps, banking systems, and large backends. Verbose but fast and reliable. Not related to JavaScript despite the name.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'SQL', plainDefinition: 'Structured Query Language — how you read and write data in relational databases. SELECT, INSERT, UPDATE, DELETE are the core commands. Required knowledge for any backend work.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Rust / Go', plainDefinition: 'Modern systems languages. Rust prioritizes memory safety with zero-cost abstractions; Go prioritizes simplicity and fast concurrency. Both are fast alternatives to C++.', category: 'general', createdAt: now(), updatedAt: now() },

  // Frontend
  { id: uid(), term: 'React', plainDefinition: 'Meta\'s library for building UIs from reusable components. Dominant in the industry. Most frontend frameworks (Next.js, Remix) build on top of it.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Next.js', plainDefinition: 'Framework built on React by Vercel. Adds file-based routing, server-side rendering, and one-command deployment. The standard for production React apps.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Vue / Svelte', plainDefinition: 'Alternatives to React for building UIs. Vue is approachable and widely used; Svelte compiles the framework away entirely for leaner, faster output.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Tailwind CSS', plainDefinition: 'Utility-first CSS framework. Style with short class names (text-sm, flex, bg-blue-500) directly in HTML/JSX instead of separate CSS files.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'shadcn/ui', plainDefinition: 'A collection of copy-paste React components styled with Tailwind. You own the code — paste it into your project rather than installing a black-box library.', category: 'general', createdAt: now(), updatedAt: now() },

  // Backend / Databases
  { id: uid(), term: 'Node.js', plainDefinition: 'A runtime that lets JavaScript run outside the browser, on a server. Enables full-stack JS apps and powers most modern JS tooling (npm, Vite, etc.).', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Supabase', plainDefinition: 'Open-source backend-in-a-box: PostgreSQL database, auth, file storage, and auto-generated APIs. The go-to backend for quick full-stack apps.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Firebase', plainDefinition: 'Google\'s backend platform: real-time database, auth, hosting, and serverless functions. Strong for mobile apps and features that need live data sync.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'PostgreSQL', plainDefinition: 'Postgres — powerful, open-source relational database. Industry standard for production apps. Handles complex queries, JSON storage, and extensions well.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'MongoDB', plainDefinition: 'NoSQL database that stores JSON-like documents instead of rigid tables. Flexible schema; useful for rapidly evolving data structures.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Redis', plainDefinition: 'In-memory data store. Blazing fast for caching, sessions, queues, and leaderboards. Data lives in RAM so reads/writes are near-instant.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'REST API', plainDefinition: 'Standard HTTP pattern for server APIs: GET to read, POST to create, PUT/PATCH to update, DELETE to remove. The dominant API design style on the web.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'GraphQL', plainDefinition: 'Alternative to REST. Clients request exactly the data they need in a single query, avoiding over-fetching and multiple round trips to different endpoints.', category: 'infrastructure', createdAt: now(), updatedAt: now() },

  // Dev Tools
  { id: uid(), term: 'Git', plainDefinition: 'Version control system that tracks every change to your code. Lets you branch, merge, and roll back without overwriting teammates\' work.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'GitHub', plainDefinition: 'Cloud hosting for Git repositories. Adds pull requests, code review, issue tracking, and CI/CD pipelines. Where most open-source code lives.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'GitLab / Bitbucket', plainDefinition: 'GitHub competitors. GitLab is popular for self-hosted setups with built-in CI/CD; Bitbucket integrates tightly with Atlassian tools like Jira and Confluence.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'VS Code', plainDefinition: 'Visual Studio Code — Microsoft\'s free code editor. The industry default. Extensible with thousands of plugins including GitHub Copilot and Claude Code.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Cursor', plainDefinition: 'A VS Code fork with AI deeply integrated. Chat with your codebase, apply multi-file edits, and get inline completions without leaving the editor.', category: 'general', createdAt: now(), updatedAt: now() },

  // Deployment / Infra
  { id: uid(), term: 'Vercel', plainDefinition: 'One-command deployment platform built for Next.js but works with any frontend. Push to GitHub and it deploys automatically with a live preview URL.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Netlify', plainDefinition: 'Vercel competitor for frontend deployment. Easy CI/CD, serverless functions, and form handling without managing any servers.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Cloudflare', plainDefinition: 'CDN, DNS, and edge network. Makes sites fast worldwide, blocks attacks, and lets you run code at the edge (Workers) close to users.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'AWS / GCP / Azure', plainDefinition: 'The big three cloud providers (Amazon, Google, Microsoft). Offer compute, storage, databases, ML services, and everything else. Powerful but complex to configure.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Docker', plainDefinition: 'Packages your app and all its dependencies into a portable container. "Works on my machine" becomes "works everywhere" — dev, staging, and production.', category: 'infrastructure', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Kubernetes', plainDefinition: 'k8s — orchestrates containers at scale. Handles load balancing, auto-scaling, and self-healing. Essential at large scale; overkill for most small apps.', category: 'infrastructure', createdAt: now(), updatedAt: now() },

  // Package Managers
  { id: uid(), term: 'npm / yarn / pnpm / bun', plainDefinition: 'JavaScript package managers that install and manage code libraries. npm is the default; bun is the fast modern newcomer. All read from package.json.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'pip', plainDefinition: 'Python\'s package manager. pip install requests adds any library from PyPI (Python\'s public package registry).', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Homebrew', plainDefinition: 'Mac package manager. brew install node installs developer tools system-wide without manual downloads or PATH wrestling.', category: 'general', createdAt: now(), updatedAt: now() },

  // Auth & Payments
  { id: uid(), term: 'Clerk / Auth0', plainDefinition: 'Drop-in authentication services. Add login, signup, OAuth (Google/GitHub), and user management to your app without building any of it yourself.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Stripe', plainDefinition: 'Payments API. The industry standard for charging users. Handles cards, subscriptions, invoices, and fraud prevention with a well-designed developer experience.', category: 'general', createdAt: now(), updatedAt: now() },

  // Design
  { id: uid(), term: 'Figma', plainDefinition: 'Browser-based UI design tool. The industry standard for designing interfaces, wireframes, and prototypes before writing a line of code.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Excalidraw', plainDefinition: 'Hand-drawn-style diagramming and whiteboarding tool. Great for quick architecture sketches and system diagrams that don\'t need to look polished.', category: 'general', createdAt: now(), updatedAt: now() },

  // Editor / Workflow Extras
  { id: uid(), term: 'Linter', plainDefinition: 'ESLint — static analysis tool that flags bad, buggy, or stylistically inconsistent code before you run it. Like a spell-checker for code.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Formatter', plainDefinition: 'Prettier — auto-formats code consistently on save. Eliminates style debates so every developer\'s code looks the same regardless of how they typed it.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'CI/CD', plainDefinition: 'Continuous Integration / Continuous Deployment — automated pipelines that run tests and deploy your app on every code push. Catches regressions before they reach production.', category: 'infrastructure', createdAt: now(), updatedAt: now() },

  // File Types — Code
  { id: uid(), term: '.html', plainDefinition: 'Webpage structure file. Contains HTML markup that defines a page\'s content and elements.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.css', plainDefinition: 'Stylesheet file. Controls visual presentation — colors, fonts, layout, and spacing.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.js', plainDefinition: 'JavaScript file. Runs in browsers or Node.js for interactive behavior and server logic.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.jsx', plainDefinition: 'JavaScript + React syntax. Contains React component code with HTML-like JSX markup mixed in.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.ts / .tsx', plainDefinition: 'TypeScript files. .ts for plain TypeScript, .tsx for TypeScript with React/JSX. Type-safe alternatives to .js and .jsx.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.py', plainDefinition: 'Python script or module. The standard file extension for all Python code.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.java', plainDefinition: 'Java source file. Contains Java class definitions compiled to bytecode that runs on the JVM.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.rs', plainDefinition: 'Rust source file. Compiled to native machine code with guaranteed memory safety.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.go', plainDefinition: 'Go source file. Compiled to a single fast binary; popular for CLI tools, APIs, and services.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.sql', plainDefinition: 'SQL file containing database queries or schema definitions. Run against a database to create tables or fetch data.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.sh', plainDefinition: 'Shell script. A sequence of terminal commands saved as a file. Common for build automation, setup scripts, and CI pipelines.', category: 'general', createdAt: now(), updatedAt: now() },

  // File Types — Config & Data
  { id: uid(), term: '.json', plainDefinition: 'JSON file — structured key/value data in text form. The most common config format and API data format in web development.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.yaml / .yml', plainDefinition: 'YAML config file — human-readable alternative to JSON. Used by GitHub Actions, Docker Compose, Kubernetes, and most CI/CD tools.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.toml', plainDefinition: 'TOML config file. Common in Rust (Cargo.toml) and Python (pyproject.toml). Readable and unambiguous.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.xml', plainDefinition: 'XML file — older verbose structured data format. Still common in Java projects, Android configs, and some enterprise tools.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.csv', plainDefinition: 'Comma-separated values — tabular data as plain text. Opens in Excel; used for data exports, imports, and feeding datasets to scripts.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.env', plainDefinition: 'Environment variables file. Stores secrets (API keys, DB URLs) outside your code so they never get committed to Git.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.gitignore', plainDefinition: 'Tells Git which files and folders to skip — node_modules, .env files, build outputs. Keeps your repo clean and secrets safe.', category: 'general', createdAt: now(), updatedAt: now() },

  // File Types — Project Files
  { id: uid(), term: 'package.json', plainDefinition: 'Node/JS project manifest. Lists dependencies, scripts (npm run dev), and project metadata. The entry point to any JavaScript project.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'package-lock.json', plainDefinition: 'Lockfile for exact JS dependency versions. Ensures everyone on the team installs identical packages. Commit this; don\'t edit it manually.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'requirements.txt', plainDefinition: 'Python dependency list. pip install -r requirements.txt installs everything at once. The Python equivalent of package.json.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'Dockerfile', plainDefinition: 'Instructions to build a Docker container image — defines the OS, installs dependencies, and sets the command to run your app.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'README.md', plainDefinition: 'A project\'s front-page explainer in Markdown. First thing visitors see on GitHub. Should explain what it does, how to install it, and how to use it.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: 'LICENSE', plainDefinition: 'Legal file declaring terms for using or redistributing the code. MIT, Apache 2.0, and GPL are common open-source licenses.', category: 'general', createdAt: now(), updatedAt: now() },

  // File Types — Docs & Writing
  { id: uid(), term: '.md', plainDefinition: 'Markdown file. Plain text with light formatting syntax (# headings, **bold**, - lists). Renders nicely on GitHub and in documentation tools.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.mdx', plainDefinition: 'Markdown + React components. Write documentation in Markdown but embed interactive React components too. Common in Next.js docs sites.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.txt', plainDefinition: 'Plain text file. No formatting. Universal — every OS and program can read it.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.pdf', plainDefinition: 'Portable Document Format. Preserves exact layout across all devices and operating systems. Not easily editable — meant for reading and sharing final output.', category: 'general', createdAt: now(), updatedAt: now() },

  // File Types — Media
  { id: uid(), term: '.png', plainDefinition: 'Lossless image format. Best for screenshots, logos, and images with transparency. Larger file size than JPEG but no quality loss on compression.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.jpg / .jpeg', plainDefinition: 'Lossy compressed image format. Best for photos — much smaller file size than PNG but loses some quality. The web default for photographs.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.svg', plainDefinition: 'Scalable Vector Graphics — vector image format defined in XML. Scales to any size without pixelating. Perfect for logos, icons, and illustrations.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.webp', plainDefinition: 'Modern compressed image format from Google. Smaller than PNG or JPEG at similar quality. Supported in all modern browsers; the preferred web image format.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.gif', plainDefinition: 'Animated image format limited to 256 colors. Universally supported for short looping animations. Often replaced by .mp4 or .webm for better quality.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.mp4', plainDefinition: 'Most common video container format. Used for web video, screen recordings, and general video sharing. Widely supported across browsers and devices.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '.mp3 / .wav', plainDefinition: 'Audio formats. MP3 is compressed (smaller files, slight quality loss); WAV is uncompressed (larger files, lossless). MP3 for distribution, WAV for production work.', category: 'general', createdAt: now(), updatedAt: now() },

  // File Types — Build Outputs
  { id: uid(), term: '.min.js / .min.css', plainDefinition: 'Minified production code. Whitespace and comments stripped out to reduce file size for faster browser loading. Never edit these directly — edit the source files.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/dist or /build', plainDefinition: 'The final compiled output folder, ready to deploy. Generated by npm run build. Contains everything needed for production — never edit files here directly.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/node_modules', plainDefinition: 'Folder where npm/yarn installs all JS dependencies. Can be hundreds of MBs. Always in .gitignore — regenerate it anytime with npm install.', category: 'general', createdAt: now(), updatedAt: now() },

  // Claude Code Slash Commands
  { id: uid(), term: '/help', plainDefinition: 'Claude Code command: lists all available commands and their descriptions.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/clear', plainDefinition: 'Claude Code command: clears the conversation history and frees up context window space for a fresh start.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/compact', plainDefinition: 'Claude Code command: summarizes the current conversation to save tokens while preserving important context.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/model', plainDefinition: 'Claude Code command: switches between models (Opus, Sonnet, Haiku) mid-session.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/config', plainDefinition: 'Claude Code command: views or edits Claude Code settings.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/cost', plainDefinition: 'Claude Code command: shows token usage and estimated API cost for the current session.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/init', plainDefinition: 'Claude Code command: generates a CLAUDE.md file documenting the current project\'s structure, conventions, and commands for future sessions.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/memory', plainDefinition: 'Claude Code command: views or edits what Claude Code remembers about the project.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/review', plainDefinition: 'Claude Code command: asks Claude to code-review recent changes in the working directory.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/pr_comments', plainDefinition: 'Claude Code command: fetches pull request comments from GitHub for the current branch.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/bug', plainDefinition: 'Claude Code command: reports a bug to Anthropic directly from the session.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/login', plainDefinition: 'Claude Code command: authenticates your Anthropic account.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/logout', plainDefinition: 'Claude Code command: signs out of your Anthropic account.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/exit / /quit', plainDefinition: 'Claude Code command: ends the current session and exits the CLI.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/mcp', plainDefinition: 'Claude Code command: manages MCP server connections — add, remove, or inspect connected tools.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/permissions', plainDefinition: 'Claude Code command: controls which tools, commands, and folders Claude can access in this project.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/vim', plainDefinition: 'Claude Code command: toggles Vim keybindings for text input in the prompt.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/add-dir', plainDefinition: 'Claude Code command: adds another directory to Claude\'s working scope for the session.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/ide', plainDefinition: 'Claude Code command: connects Claude Code to your IDE (VS Code, Cursor, etc.) for synchronized editing.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/hooks', plainDefinition: 'Claude Code command: configures hooks — shell commands that run automatically before or after Claude uses a tool.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/agents', plainDefinition: 'Claude Code command: manages sub-agents for delegated tasks that run in parallel or independently.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/resume', plainDefinition: 'Claude Code command: resumes a previous Claude Code session with its history and context.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/status', plainDefinition: 'Claude Code command: shows current session info — active model, tokens used, and working directory.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/doctor', plainDefinition: 'Claude Code command: diagnoses installation or configuration issues with Claude Code.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/upgrade', plainDefinition: 'Claude Code command: updates Claude Code to the latest version.', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/terminal-setup', plainDefinition: 'Claude Code command: configures terminal key bindings for Claude Code (e.g., option+enter for newline).', category: 'general', createdAt: now(), updatedAt: now() },
  { id: uid(), term: '/export', plainDefinition: 'Claude Code command: exports the current conversation to a file.', category: 'general', createdAt: now(), updatedAt: now() },
];
